### ISSUE TITLE
confused withe the mechanism,always excess 1000.

### ISSUE THREAD

**Issue by guanglinlv** [openresty/lua-resty-limit-traffic#5]
Hi,

thanks for the wonderful project, it help us find the ability of flow control in openresty! 

i am trying to use `limit_req` as the [example](https://github.com/openresty/lua-resty-limit-traffic/blob/master/lib/resty/limit/req.md#synopsis) way. however i got 99/100  rejected requests.

reproduce step:
1. take the same code with [example](https://github.com/openresty/lua-resty-limit-traffic/blob/master/lib/resty/limit/req.md#synopsis)
2. simulate the concurrency using `ab -n 100 -c 10`
3. check the ab report `Non-2xx responses: 99`

and i also add some debug log after line [req.lua#L94](https://github.com/openresty/lua-resty-limit-traffic/blob/master/lib/resty/limit/req.lua#L94) 

```
2016/03/22 00:19:12 [warn] 4570#0: *9 [lua] req.lua:95: incoming(): incomming,excess: 1000,elapsed: 0,rate: 200000, client: 9.91.39.111, server: _, request: "GET /scm/test HTTP/1.0", host: "9.91.39.77"
2016/03/22 00:19:12 [warn] 4570#0: *10 [lua] req.lua:95: incoming(): incomming,excess: 1000,elapsed: 0,rate: 200000, client: 9.91.39.111, server: _, request: "GET /scm/test HTTP/1.0", host: "9.91.39.77"
```

i'm confused the formula `excess = tonumber(rec.excess) - rate * abs(elapsed) / 1000 + 1000`

did i miss some import information aboubt `limit_req` ?

Thanks.

**Comment by agentzh** [comment]
@guanglinlv You seem to misinterpret the request rate here. Tools like `ab` always tries to send requests as fast as possible, which means it may always exceed the request rate if your response time is fast enough. In other words, the request rate honored by this library (as well as the standard ngx_limit_req module in the nginx core) is calculated by the interval between successive requests, that is, the requests must come in relatively evenly. For example, if the request rate is 10 r/s, then the interval between two successive requests should be larger than 0.1s (or 100ms) to avoid triggering delaying or even rejecting. Because `ab` always tries to maximize the request rate and one cannot control the request rate sent by `ab`, it's not the right tool to test this.

**Comment by guanglinlv** [comment]
@agentzh , thanks. i‘ve guessed it. but i'm not sure what is the suited case for that limiter. at my side,i need a limiter that limit the requests per second (RPS) explicitly. so, should we add a new limiter like that? 

the following is my thought about the limiter of RPS, any suggestion is very thankful.

```lua
function _M.incoming(self, key, commit)
    local v = self.dict:get(key)
    if v then
        local vv,err = dict:incr(key,1)
        if vv then excess = tonumber(vv) - self.rate end
        if excess < 0 then excess = 0 end
        if excess > self.burst then return nil, "rejected" end
    else
        local ok,err = self.dict:safe_set(key,1,self.period)
    end
    return (excess * self.period) / self.rate, excess
end
```

**Comment by agentzh** [comment]
@guanglinlv I'm not sure what you're trying to here. If you are just trying to make ab happy, then I'm not sure that's the right thing to do. When someone is pointing an ab at your site, that *is* an DoS attack. Another approach is to set a high burst parameter so that your limiter won't bail out too easily with something like "ab".

**Comment by agentzh** [comment]
@guanglinlv BTW, your code snippet looks wrong to me.

**Comment by guanglinlv** [comment]
@agentzh yes, that limiter is filter some attack like Dos. it's useful to avoid flooding the application server. it means that limit the number of some request up to `self.rate+self.burst` in some period. for example, 800+200 requests with `http://domain/order` or `http://domain/shopcart` in one second.

okay, thank you very much anyway. i'm closing the ticket here...
